Проверяем рабочий процесс
htmlacademy-htmlcss/1900049-device-32 pull request #1
Opened 2021-09-21 17:35 UTC by Luna100500

---
:mortar_board: [Проверяем рабочий процесс](https://up.htmlacademy.ru/htmlcss/32/user/1900049/tasks/2)

:boom: https://htmlacademy-htmlcss.github.io/1900049-device-32/1/

2021-09-22 21:16 UTC, Luna100500 commented
Привет! Можно уточнить, со ссылкой на что?)

вт, 21 сент. 2021 г. в 20:42, Dima ***@***.***>:

> Привет! Давай сделаем меня тоже со ссылкой :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/htmlacademy-htmlcss/1900049-device-32/pull/1#issuecomment-924269095>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVSWCV5CCXHTHLN45FYD423UDDGYJANCNFSM5EPBSXEA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-23 06:36 UTC, Dima-Dim commented
> Привет! Можно уточнить, со ссылкой на что?)

Отличный вопрос! ;)
Со ссылкой на мой профиль https://htmlacademy.ru/profile/dima

2021-09-23 06:38 UTC, Dima-Dim requested changes
Ссылку вижу, молодец, но давай сделаем её так же как это сделано у тебя, в строке Студент. Т.е. ссылкой является имя и фамилия.

2021-09-23 16:08 UTC, Luna100500 commented
Здравствуйте!) Готово! Долго не могла понять что же не так... до тех пор
пока не скопировала строку с моей фамилией и внесла изменения)  Проблемой
оказался пробел, который я не заметила (я пока полный 0 в программировании)
Т.к. я редактирую код в VS Code, я не могу увидеть изменения в конечном
результате до тех пор, пока мой Комит не окажется на портале. Наверное есть
какая-то возможность посмотреть что получилось до того как я отправлю
результат вам?)


чт, 23 сент. 2021 г., 8:38 Dima ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Ссылку вижу, молодец, но давай сделаем её так же как это сделано у тебя, в
> строке Студент.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/htmlacademy-htmlcss/1900049-device-32/pull/1#pullrequestreview-761633883>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVSWCVYFRWA5I4W4SUBJLKDUDLDNTANCNFSM5EPBSXEA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-24 09:16 UTC, Dima-Dim commented
> Здравствуйте!) Готово! Долго не могла понять что же не так... до тех пор пока не скопировала строку с моей фамилией и внесла изменения) Проблемой оказался пробел, который я не заметила (я пока полный 0 в программировании) Т.к. я редактирую код в VS Code, я не могу увидеть изменения в конечном результате до тех пор, пока мой Комит не окажется на портале. Наверное есть какая-то возможность посмотреть что получилось до того как я отправлю результат вам?)

Привет! Классно что справилась с проблемой, нашла и решила её.
По поводу смотреть что получилось, наверняка для VS Code есть какой-нибудь плагин для просмотра md файлов.

2021-09-24 09:17 UTC, Dima-Dim commented
После внесения правок не забывай отправлять задание на проверку.

2021-09-24 09:17 UTC, Dima-Dim approved these changes

2021-09-24 19:28 UTC, merged